long calc_area(int width, int height);
int is_odd(int n);
long range_sum(int n);
long squared_sum(int n);
void analyze_rectangle(int width, int height, long *area, long *perimeter);
int count_steps(int n);
int digit_count(int n);
int array_even_count(int *array, int n);
int array_min_value(int *array, int n);
int array_is_sorted(int *array, int n);
void convert_array(int *array, int n);
int array_distinct_count(int *array, int n);
int count_letters(char *string, char letter);
int count_words(char *words);
int is_palindrome(char *word);
int check_anagrams(char *word1, char *word2);
int valid_student_number(char *number);
